# Generated by Django 5.1.7 on 2025-03-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('', ''), ('Tech', 'Tech'), ('Business', 'Business'), ('Social', 'Social'), ('Art', 'Art'), ('Trade Expos', 'Trade Expos'), ('Education', 'Education')], max_length=100),
        ),
    ]
